### PR TITLE
fix:  Auto open browser in Linux

### PR DESCRIPTION
**Pull request by Spagett1**
## Description

This changes the files run-dev.sh and ci/start.sh to instead of calling open directly check if it is running on a darwin system.

If it is it will proceed with the previous open command however if it is on a linux system it will call xdg-open instead. 

This is because the open command doesnt exist on linux and is just called xdg-open.

This will not work on extremely minimal setups so i do think it would be good to still mention localhost:8080 in the install section however it will enable it to work on 95% of systems. 

## Related Issues

https://github.com/builder555/PineSAM/issues/136

## Screenshots

image

## Checklist

- [x ] I have tested my changes locally and they work as expected. 
**I do not have a macos system however as i am following the same if check as line 10 of the start.sh script i see no reason for it to not work.**
- [ x] I have updated the documentation, if applicable.
- [x ] I have added appropriate tests, if applicable.
- [x ] I have run the linter and fixed any issues, if applicable.

## Other information

Please include any other pertinent information.

### CODE REVIEW

**Comment by builder555** [comment]
@Spagett1 can you please make the PR into dev instead of master? that way it'll go through the proper workflow

**Comment by Spagett1** [comment]
Closing cause i didnt realise it was wanted to go into dev and now its trying to pull in extra commits.

**Comment by builder555** [comment]
> @builder is there a submission guide somewhere? could add that all PR need to be submitted in /dev?
> 
> I'll put a note at bottom of the Readme page

I added a comment to the top of the PR template

**Comment by River-Mochi** [comment]
@builder what is the  title name you want for  doc updates?

fix:   for bugs
feat: for  new feature.

**Comment by builder555** [comment]
go with "fix:", i don't think updating docs qualifies as features.

**Pull request closed without merging**
