### PR TITLE
Use mkdocs as documentation software instead of GitHub wiki

### PR DESCRIPTION
**Pull request by MagicLike**
## Description

I added [mkdocs (material)](https://squidfunk.github.io/mkdocs-material) with all assets and my customisations to the repo and used the elements from the wiki.
This is in a early state and needs improvement.
A standalone build of the current state can be found here: https://pinesam-docs.mgclk.li
If merged, the hosting will be handled via GitHub Actions and GitHub Pages probably over the URL `https://builder555.github.io/PineSAM`.

_(If you need prove, that the Domain belongs to me, take a look at my [Keyoxide profile](https://keyoxide.org/contact@magiclike.net))_

## Screenshots
grafik
grafik
grafik
grafik

## Checklist

- [x] I have tested my changes locally and they work as expected.
- [x] I have updated the documentation, if applicable.

### CODE REVIEW

**Comment by builder555** [comment]
that looks very nice! I don't think I'll have time to work on it until the weekend, I don't know if @River-Mochi wants to take a stab in the mean time.

**Comment by River-Mochi** [comment]
would love to use anything else.  just used github Wiki  because it's there but it's not great and doesn't let use do much at all.

**Comment by MagicLike** [comment]
> if you activate it then between  @MagicLike who seems to know how to use MKdocs and me (I can provide the data for the documents)  we can point people there instead of the Wiki.

@builder555 It would be nice if you could add me as contributor to the repo, so I will be able to commit to the docs directely. 😅

> Magic, I used the wiki only because it's what we had available just to get basic usage guide going. would love to learn how to do  MkDocs and  I think  IronOS  uses the theme called "Read the Docs" .   but there are different themes.

Regarding themes: I have chosen the theme and 'add-on' / soft fork MkDocs Material which you can see active on my demo and screenshots.

**Comment by River-Mochi** [comment]
Does the MKdocs copy directly from the PineSAM wiki ?  would it be better to make the document as  docs inside a documents folder that MKdocs  points to or leave in Wiki?

**Comment by River-Mochi** [comment]
> Just take a look at my branch: I copied all wiki entries into their appropriate .md file and also copied all images needed in their respective folder. I usually put all files and stuff in a folder named "assets" and make sub-folders for the specific file type and the respective belongingness... It has nothing to do with GH Wiki. It will be hosted as a website through GH pages in this case. (It could also be hosted on a own webserver)

then where would I edit the documents? 
For example,  in Ralim's IronOS, I still edit the documents right inside the Github repo where they sit in documentation folder just like all the other collaborators/translators do.  Ralim has it set up somehow that whatever we edit there then  get's updated on the MKdocs website he set up.

1. Direct example, currently, for IronOS,   I edit all the documents directly in here: https://github.com/Ralim/IronOS/tree/dev/Documentation

2. Then after Ralim accepts my PR edits,  it goes here: 
https://ralim.github.io/IronOS/
but on that  "io"  page  we can not currently edit.  we still do all our edits directly in the github ralim's ironOS.   the Edit button does not even work  on the "io" page to go to correct place yet (most likely ralim no time to fully implement since he only a few months ago   showed docs in MKDocs view - but they are all still in Github repo).

**Comment by MagicLike** [comment]
> @MagicLike basically we submit a PR, and then  wait for builder to approve or make changes. 
>  that is how all the contributors are doing it and it's safer for builder's pineSAM especially since there are only a few contributors so far.

Alright - I did not take a closer look on how you are a contributer to PineSAM.

> becoming a contributor is easy,   just make a fork of PineSAM, and then submit a PR  with code changes [...]

Ik ik... Made enough contributions to know the system 😄
(I just thought in that moment to use the "invite contributors" function)
 
> I think when Builder has time he was going to implement something that gives credit to the contributors in the releases similar to how other repos have it. 

👍

**Comment by MagicLike** [comment]
I will open my PR for merge today (maybe in a hour or so.

@builder555 You need to make sure GitHub Actions are enabled for this repo and that the Actions script, that comes with this PR gets enabled.

**Comment by MagicLike** [comment]
> alright then the Wiki page has to go away and get copied into a document in a /docs folder. 

Already copied them 😅

> Also the way  that MKDocs looks, I thing the sections and the way I have the Roman numbers could be changed. I only did that in Wiki because I had no good ways/tools  to separate the info.   with MKdocs it will be lot easier to make data organized and clean.

Just take a look at my [demo](https://pinesam-docs.mgclk.li) (I built this from my current changes), I have enabled latin numbers for numbering the sections...

**Comment by River-Mochi** [comment]
for background, the reason Builder555 asked me to look at this change is bc I completely wrote the current wiki usage guide.   I'm all for it 👍  ⭐  💜 🐧 💙

**Comment by MagicLike** [comment]
@River-Mochi Ok, I have moved Usage and HUD together and moved the TOC... What do you think? (before I commit)
grafik
grafik
grafik

**Comment by MagicLike** [comment]
> how did you add the Icon with the Dark/light mode, we should have this for the IronOS documents too. maybe you could submit a PR over there to add this to current page: https://ralim.github.io/IronOS/
> 
> image

I don't think this is possible, as Ralim uses the RTD theme which does not have a integrated dark theme...

**Comment by MagicLike** [comment]
> how did you add the Icon with the Dark/light mode, we should have this for the IronOS documents too. maybe you could submit a PR over there to add this to current page: https://ralim.github.io/IronOS/
> 
> image

I don't think this is possible, as Ralim uses the RTD theme which does not have a integrated dark theme...

**Comment by MagicLike** [comment]
@River-Mochi Ok, just committed... I will open this PR now for review... @builder555

**Comment by builder555** [comment]
@MagicLike does the job need to run on schedule or can it be done on merge to master? similar to the release job? I'm fine to run it either way, just wondering what's more efficient

**Comment by MagicLike** [comment]
> @MagicLike does the workflow need to run on schedule or can it be done on merge to master? similar to the build workflow? I'm fine to run it either way, just wondering what's more efficient. 
> 
> running the job "on push" to master isn't going to work because I avoid commits directly to master unless there's some issue with the workflow.

I set it to run on push to '/docs' & 'mkdocs.yml', which should include PRs. (Am I right with this one?) Also it will run every Monday at 0:00 to catch MkDocs Material updates without human intervention.

**Comment by River-Mochi** [comment]
@MagicLike   make a fork  of  /dev ,   typically builder likes changes  for PR to come in on  /dev first. 

I try to keep both my  fork of  /dev and all  other branches  synced with  PineSAM - but only submit  PR to  /dev. 

then  builder approves it  and moves to main.   This is also how  Ralim does it on IronOS.  we only submit PR to /dev but never main and then somehow  Ralim gets it over there.

**Comment by builder555** [comment]
let's try and see what happens

**Comment by River-Mochi** [comment]
can see an example of how it's done here 

https://github.com/Ralim/IronOS/actions
Top one right now   called  "pages build and deployment"  is what  I think the  updating of all the IronOS MKDocs to make the new github-pages.

image

**Comment by MagicLike** [comment]
@builder555 What font does PineSAM use?

**Comment by builder555** [comment]
@MagicLike for the logo - `Righteous`, for the rest, it's whatever bulma css uses, from what i see it's `BlinkMacSystemFont,-apple-system,"Segoe UI",Roboto,Oxygen,Ubuntu,Cantarell,"Fira Sans","Droid Sans","Helvetica Neue",Helvetica,Arial,sans-serif`

**Comment by MagicLike** [comment]
> @MagicLike for the logo - `Righteous`, for the rest, it's whatever bulma css uses, from what i see it's `BlinkMacSystemFont,-apple-system,"Segoe UI",Roboto,Oxygen,Ubuntu,Cantarell,"Fira Sans","Droid Sans","Helvetica Neue",Helvetica,Arial,sans-serif`
> 

@builder555 
Ok, thx - maybe I will change the fonts of the docs later... It seems like it did not get deployed, nor that the action is activated. May you try to merch it into main to see of it changes anything?

**Comment by builder555** [comment]
it's merged into master already, i think the issue is the trigger - it needs to be on pull request closed, because i don't push directly to master.

**Comment by builder555** [comment]
done. ran it manually

**Comment by MagicLike** [comment]
> done. ran it manually

It seems like GH pages did not pick it up correctly - could you please check the repo settings for pages?

**Comment by builder555** [comment]
looks like it worked https://builder555.github.io/PineSAM/

**Comment by MagicLike** [comment]
NIce! :+1:

**Comment by MagicLike** [comment]
Now we can get rid of the wiki...

**Comment by River-Mochi** [comment]
> Now we can get rid of the wiki...

not yet  the current  MKdocs needs some work and clean up on the categories. I can look at it later tonight  as there was some information I needed to add to the documents.

I'd like to leave the Wiki in place  as it's not harming anything and for now it works if people do wander over there,  it has correct information.

**Comment by MagicLike** [comment]
> > Now we can get rid of the wiki...
> 
> not yet, the current MKdocs needs some work and clean up on the categories. I can look at it later tonight as there was some information I needed to add to the documents.
> 
> I'd like to leave the Wiki in place for now as it's not harming anything and it works if people do wander over there, it has correct information. technically could just leave the Wiki alone for a while until the MkDocs has matured a while.

Alright, if you need any help with using MkDocs Material, just hit me up here, over the Fedi or E-Mail!
If it is ok, I would add a Link to the new docs to the wiki later...

**Comment by River-Mochi** [comment]
will do.   I have to work  on PineFlash right now bc as of 4 hours ago, it now supports V2  for auto fetching ironOS, and doing updates.  the docs have to wait until I can finish that since goal is to have PineFlash ready before the 2.21  comes out which is very  soon. 

So many people  who are not used to using terminal commands have issues updating with Blips; if pineflash works out, this will reduce a lot of headaches for volunteers and IronOS too. 

Pineflash only works for linux/MacOS  right now so I'm also trying see if anyone can help port it to windows in case spagett doesn't have time.

**Pull request merged**
