### PR TITLE
fix Mkdocs 

### PR DESCRIPTION
**Pull request by River-Mochi**
## Description

- add content for new Mkdocs
- fix the main index page for mkdoc to have content 
- relocate images to inside  /docs  as a shared  resource for github and mkdocs  to remove duplicate locations.

### CODE REVIEW

**Review by MagicLike — COMMENTED** [review]
@River-Mochi The images don't belong just in the docs folder, but into the `docs/assets/img` folder. Please change it to ensure continuity. (It can also be a bit confusing, as the images are now there twice.)

**Comment by River-Mochi** [comment]
I'm moving them out of the main repo so we have less duplicates step1 I just moved it like it is  since it was named images

**Comment by River-Mochi** [comment]
> The images don't belong just in the docs folder, but into the `docs/assets/img` folder. Please change it to ensure continuity. (It can also be a bit confusing, as the images are now there twice.)

duplication problem happened already when  /doc/img  copied all same images we have in images.  so I'm slowing moving it to just one place.  step 1  I moved the images as is into  docs

**Comment by River-Mochi** [comment]
later today when I have time I'm going to compare  what  my original images I made were and what is in /doc/img  

duplication is the problem I'm trying to solve since  that /doc/img folder was made  and the original /images folder was not changed or deleted.   this takes a little times since all the  links to original images need to change also. that probably should have been done when original  /doc/img  folder was made.

**Comment by River-Mochi** [comment]
is there any reason why the  images are all a single image in a separate folder? 
image

why can't they all be  simply  inside  /img  

this seems complex as the image names  already say what they do.

**Pull request merged**
